### ISSUE TITLE
Inheritance chain

### ISSUE THREAD

**Issue by mafaca** [DaZombieKiller/TypeTreeDumper#10]
https://github.com/DaZombieKiller/TypeTreeDumper/blob/a7657a1de2ed023e441b2fa4a54ad4d46719ae86/Unity/RuntimeTypeInfo.cs#L22
This property is always null. So it doesn't show inheritance chain in dump file.

**Comment by DaZombieKiller** [comment]
Looks like it was accidentally made a read-only property instead of redirecting to the interface. I'll investigate this later today.

**Comment by DaZombieKiller** [comment]
Fixed in https://github.com/DaZombieKiller/TypeTreeDumper/commit/c87621328613bfa43bfaa5d0c6274fa1e22acdac
