### ISSUE TITLE
2017.3.0b1

### ISSUE THREAD

**Issue by mafaca** [DaZombieKiller/TypeTreeDumper#11]
For some reason this tool fails to dump 2017.3.0b1 editor version. It doesn't create output dump file

**Comment by DaZombieKiller** [comment]
Do you get any exception messages in the output, or does it simply not output any dump files?

**Comment by mafaca** [comment]
Empty console. No exceptions.
2017.3.0b11 fails as well

**Comment by mafaca** [comment]
I use modified dumper, so for in my case it calls ExportStructDump only.

**Comment by DaZombieKiller** [comment]
It's possible that 2017.3 has a different layout for the `TypeTree` structure, which is causing the dumper to fail.

**Comment by DaZombieKiller** [comment]
@mafaca Actually, do you have a leftover `DummyProject` folder from dumping a newer version of Unity? It seems that can cause dumping to silently fail. Deleting that folder should allow it to work.

**Comment by mafaca** [comment]
Thanks, it helped. This is really weird since I used dumper for older version of editor and unity usually has no problem upgrading project.

**Comment by DaZombieKiller** [comment]
This might be fixable without deleting the `DummyProject` directory by passing the `-accept-apiupdate` argument to Unity from the bootstrapper. That most likely wouldn't work with downgrading though, which would still require the folder to be removed.

**Comment by mafaca** [comment]
> Thanks, it helped. This is really weird since I used dumper for older version of editor and unity usually has no problem upgrading project.

Hmm.... unfortunately it helped only for 2017.3.0b11. 2017.3.0b1 still fails even when i delete DummyProject folder.

**Comment by DaZombieKiller** [comment]
I'll download 2017.3.0b1 right now so I can investigate, if deleting the folder didn't work then it must have some structure differences (or if we're _really_ unlucky, some kind of obfuscation like Unity 3.x has).

**Comment by DaZombieKiller** [comment]
2017.3.0b1 works on my end, but I did notice that sometimes it fails with no output. I'm not sure what the cause is, but if you try to run it a few more times it should work.

**Comment by mafaca** [comment]
I checked log file. Unity is unable to start package manager. And it happens in 100% cases when I launch dumper. Launching editor from cmd work in 50% cases. It really weird. Anyway, it is not dumper issues so i'm closing it. thanks for help

**Comment by DaZombieKiller** [comment]
If the package manager is the cause, then passing `-noUpm` on the command line to Unity from the bootstrapper should fix it.

**Comment by DaZombieKiller** [comment]
Nevermind, `-noUpm` was unfortunately only added in Unity 2018.1 onwards, so a fix would require hooking and stubbing out whatever function attempts to initialize it.

**Comment by DaZombieKiller** [comment]
I've added the `-noUpm` change in https://github.com/DaZombieKiller/TypeTreeDumper/commit/94d713d2cec41c20c4a1bfb12e37ee56736baea3, but a fix for 2017.x will require some research.

**Comment by DaZombieKiller** [comment]
Interesting. Does it still work if you keep the call to it in `HandleEngineInitialization`?

**Comment by mafaca** [comment]
Yes, it work fine if I keep the call in  HandleEngineInitialization . But constructor and Run leads to stuck

**Comment by DaZombieKiller** [comment]
I'm guessing it's because `FreeConsole`/`AttachConsole` invalidates the native `stdin`/`stdout`/`stderr` handles or something, which causes an error when Unity tries to attach to the package manager. If that's the case, those handles would also need to be updated in `AttachToParentConsole`.

**Comment by DaZombieKiller** [comment]
Fixed in https://github.com/DaZombieKiller/TypeTreeDumper/commit/cde9611a40abf3559d6668682b8026aa6266a812.
