### ISSUE TITLE
[2017.x] Unity Package Manager initialization failures will cause dumps to fail

### ISSUE THREAD

**Issue by DaZombieKiller** [DaZombieKiller/TypeTreeDumper#12]
If the Unity Package Manager fails to initialize, the dump will fail because `AfterEverythingLoaded` never gets called.

https://github.com/DaZombieKiller/TypeTreeDumper/commit/94d713d2cec41c20c4a1bfb12e37ee56736baea3 introduced a change that will fix this for 2018.1 and higher, but 2017.x does not support the `-noUpm` command line argument.

A proper fix will likely require hooking and stubbing whichever function attempts to initialize UPM.

**Comment by DaZombieKiller** [comment]
Fixed in https://github.com/DaZombieKiller/TypeTreeDumper/commit/cde9611a40abf3559d6668682b8026aa6266a812.

**Comment by mafaca** [comment]
fix works for 2017.3.0bx but doesn't work for 2017.2.0bx. btw this version doesn't has attempt counter so it just stucks and waits infinity.

**Comment by DaZombieKiller** [comment]
Does removing `AttachToParentConsole` fix it for 2017.2? If that works I can probably just disable it on 2017.1 and 2017.2.

**Comment by mafaca** [comment]
Yes, removing AttachToParentConsole fix it

**Comment by DaZombieKiller** [comment]
I wasn't able to reproduce the hang, but I disabled `AttachToParentConsole` in the constructor and `Run` for 2017.1 to 2017.2 in https://github.com/DaZombieKiller/TypeTreeDumper/commit/9387f1e0e85acf6492da9c01a8f43a489ba1ad69
